"""01 update

Revision ID: 9258b4d11051
Revises: 342a18cb2b70
Create Date: 2020-04-01 15:00:34.527233

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9258b4d11051'
down_revision = '342a18cb2b70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('drugsets', 'date',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text("'2020-03-31 00:00:00'"))
    op.alter_column('genesets', 'date',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text("'2020-03-31 00:00:00'"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('genesets', 'date',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text("'2020-03-31 00:00:00'"))
    op.alter_column('drugsets', 'date',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text("'2020-03-31 00:00:00'"))
    # ### end Alembic commands ###
