"""02 add date

Revision ID: dc18a84a5406
Revises: 4460cbfb9f68
Create Date: 2020-04-01 17:05:45.970266

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dc18a84a5406'
down_revision = '4460cbfb9f68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drugsets', sa.Column('date', sa.DateTime(), nullable=True))
    op.add_column('genesets', sa.Column('date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    if op.get_context().dialect.driver == 'pysqlite':
        with op.batch_alter_table('drugsets') as batch_op:
            batch_op.drop_column('date')

        with op.batch_alter_table('genesets') as batch_op:
            batch_op.drop_column('date')
    else:
        op.drop_column('drugsets', 'date')
        op.drop_column('genesets', 'date')

