"""Metadata

Revision ID: 2a9652d72819
Revises: db2c2997fad2
Create Date: 2020-04-08 17:06:57.732608

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2a9652d72819'
down_revision = 'db2c2997fad2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('genesets', sa.Column('meta', mysql.JSON(), nullable=True))
    op.add_column('drugsets', sa.Column('meta', mysql.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drugsets', 'meta')
    op.drop_column('genesets', 'meta')
    # ### end Alembic commands ###
