"""Drugsets categories

Revision ID: 94ad0824ffb3
Revises: da4d5d0ac64d
Create Date: 2020-04-29 15:50:13.205737

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '94ad0824ffb3'
down_revision = 'da4d5d0ac64d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drugsets', sa.Column('category', mysql.INTEGER(display_width=11), server_default=sa.text("'1'"), autoincrement=False, nullable=False))
    op.create_table('categories',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), server_default=sa.text("'all'"), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drugsets', 'category')
    op.drop_table('categories')
    # ### end Alembic commands ###
