"""DrugEnrichr

Revision ID: 0182cee73887
Revises: 66dde3f11ecb
Create Date: 2020-05-12 18:43:16.523025

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0182cee73887'
down_revision = '66dde3f11ecb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drugsets', sa.Column('enrichrShortId', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('drugsets', sa.Column('enrichrUserListId', mysql.INTEGER(display_width=11), server_default=sa.text("'0'"), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'drugsets', type_='foreignkey')
    op.create_foreign_key('drugsets_categories_id_fk', 'drugsets', 'categories', ['category'], ['id'], onupdate='CASCADE')
    op.create_index('categories_name_uindex', 'categories', ['name'], unique=True)
    op.alter_column('categories', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text("'all'"))
    # Ideally, you should use Drugset.submit_to_enrichr()
    # on each list to fill values, but I'm kinda in a rush,
    # so not today 💁🏼‍
    print('Use Drugset.submit_to_enrichr() to fill values')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text("'all'"))
    op.drop_index('categories_name_uindex', table_name='categories')
    op.drop_constraint('drugsets_categories_id_fk', 'drugsets', type_='foreignkey')
    op.create_foreign_key(None, 'drugsets', 'categories', ['category'], ['id'])
    op.drop_column('drugsets', 'enrichrUserListId')
    op.drop_column('drugsets', 'enrichrShortId')
    # ### end Alembic commands ###
