"""Add collections

Revision ID: 86bad052438a
Revises: bd249556ad86
Create Date: 2020-11-02 17:54:40.630780

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '86bad052438a'
down_revision = 'bd249556ad86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('genesets', 'category',
                    existing_type=mysql.INTEGER(display_width=11),
                    nullable=True,
                    existing_server_default=sa.text("'1'"))
    op.alter_column('drugsets', 'enrichrUserListId',
                    existing_type=mysql.INTEGER(display_width=11),
                    nullable=True,
                    existing_server_default=sa.text("'0'"))
    op.alter_column('drugsets', 'enrichrShortId',
                    existing_type=mysql.VARCHAR(length=255),
                    nullable=True)
    op.create_index('categories_name_uindex', 'categories', ['name'], unique=True)
    op.alter_column('categories', 'name',
                    existing_type=mysql.VARCHAR(length=255),
                    nullable=True,
                    existing_server_default=sa.text("'all'"))
    op.create_table('collections',
                    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
                    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
                    sa.Column('description', mysql.TEXT(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_default_charset='latin1',
                    mysql_engine='InnoDB'
                    )
    op.create_index('collections_id_uindex', 'collections', ['id'], unique=True)
    op.create_table('sets_collections',
                    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
                    sa.Column('setId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
                    sa.Column('collectionId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['collectionId'], ['collections.id'],
                                            name='sets_columns_collections_id_fk'),
                    sa.ForeignKeyConstraint(['setId'], ['drugsets.id'], name='sets_columns_drugsets_id_fk'),
                    sa.ForeignKeyConstraint(['setId'], ['genesets.id'], name='sets_columns_genesets_id_fk'),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_default_charset='latin1',
                    mysql_engine='InnoDB'
                    )
    op.create_index('sets_columns_id_uindex', 'sets_collections', ['id'], unique=True)
    # ### end Alembic commands ###

    print('Copying categories to collections - write the code yourself, because I didn\'t')
    #
    print('Copying \'id\' and \'category\' from both sets tables to \'sets_collections\'  - write the code yourself, because I didn\'t')
    #


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('sets_columns_id_uindex', table_name='sets_collections')
    op.drop_table('sets_collections')
    op.drop_index('collections_id_uindex', table_name='collections')
    op.drop_table('collections')
    op.alter_column('categories', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text("'all'"))
    op.drop_index('categories_name_uindex', table_name='categories')
    op.alter_column('drugsets', 'enrichrShortId',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('drugsets', 'enrichrUserListId',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('genesets', 'category',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    # ### end Alembic commands ###
